on:
  schedule:
    - cron: "15 * * * *"
  push:
    branches: master

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: chmod 700 ./scripts/download_csv.sh && ./scripts/download_csv.sh
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Updates csv" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
